# -*- coding: utf-8 -*-
"""ASR_myntra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EMey0q_Oyn6W1NTbJKfCWkcdQV0CKV8f
"""
from flask import Flask
# import pandas as pd
# import re
import requests 
import string

def speech_text(text):
  tokens = text.split()
  if "page" in tokens:
    if "next" in tokens:
      return render_template("home.html")
   