# -*- coding: utf-8 -*-
"""ASR_myntra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EMey0q_Oyn6W1NTbJKfCWkcdQV0CKV8f
"""

import pandas as pd
import re
import string

def speech_text(text):
  tokens = text.split()
  if "page" in tokens:
    if "next" in tokens:
      return redirect_to_next_page
    elif "previous" in tokens:
      return redirect_to_previous_page
    elif "home" in tokens:
      return redirect_to_home_page
  elif "home" in tokens:
    return redirect_to_home_page
  elif "region" in tokens:
    if "north" in tokens:
      return region_search("north")
    if "south" in tokens:
      return region_search("soth")
    elif "east" in tokens:
      return region_search("east")
    elif "north east" in tokens:
      return region_search("northeast")
    elif "western" in tokens:
      return region_search("western")